version: '3.8'

services:
  web:
    build: ./app
    command: gunicorn cf.wsgi:application --bind 0.0.0.0:8011
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8011:8011
    env_file:
      - ./.env