version: "3.8"

services:
  web:
    build: ./app
    command: gunicorn cf.wsgi:application --bind 0.0.0.0:8011
    # command: python manage.py runserver 0:8011
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8011:8011
    restart: unless-stopped
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=candy
      - POSTGRES_PASSWORD=candy
      - POSTGRES_DB=candy
    restart: unless-stopped

volumes:
  postgres_data:
