# Generated by Django 4.2.5 on 2023-11-09 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('uid', models.CharField(max_length=6, verbose_name='NIC')),
                ('expires', models.DateField()),
            ],
        ),
    ]
