# Generated by Django 4.2.5 on 2023-11-09 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='uid',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='NIC'),
        ),
    ]
