# Generated by Django 4.2.5 on 2023-11-09 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0002_alter_status_uid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='date',
            new_name='received',
        ),
    ]
