# Generated by Django 4.2.5 on 2023-11-14 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0003_rename_date_status_received'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ('-expires',)},
        ),
    ]
