# Generated by Django 4.2.5 on 2023-09-12 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Correspondence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_on_doc', models.DateField()),
                ('date_received', models.DateField()),
                ('edrms_id', models.CharField(max_length=50, unique=True, verbose_name='EDRMS ID')),
                ('subject', models.CharField(max_length=255)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='action_list', to='letters.action')),
                ('copied_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='copied_to_list', to='letters.correspondence', verbose_name='copied to')),
                ('rec_from', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rec_from_list', to='letters.correspondence', verbose_name='received from')),
                ('sent_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_to_list', to='letters.correspondence', verbose_name='sent to')),
            ],
        ),
        migrations.CreateModel(
            name='LetterComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255)),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letter_comments', to='letters.letter')),
            ],
        ),
    ]
