# Generated by Django 4.2.5 on 2023-09-12 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='subject',
            field=models.TextField(),
        ),
    ]
