# Generated by Django 4.2.5 on 2023-09-12 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0003_alter_letter_date_on_doc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letter',
            name='copied_to',
        ),
        migrations.AddField(
            model_name='letter',
            name='copied_to',
            field=models.ManyToManyField(related_name='copied_to_list', to='letters.correspondence'),
        ),
    ]
