# Generated by Django 4.2.5 on 2023-09-13 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0004_remove_letter_copied_to_letter_copied_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='copied_to',
            field=models.ManyToManyField(blank=True, related_name='copied_to_list', to='letters.correspondence'),
        ),
    ]
