# Generated by Django 4.2.5 on 2023-09-24 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('letters', '0006_rename_lettercomments_lettercomment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lettercomment',
            options={'ordering': ['-pk']},
        ),
        migrations.AddField(
            model_name='letter',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='letter',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_by_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='letter',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='letter',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_by_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lettercomment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lettercomment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comment_created_by_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lettercomment',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='lettercomment',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comment_updated_by_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lettercomment',
            name='comment',
            field=models.TextField(),
        ),
    ]
