# Generated by Django 4.2.5 on 2023-10-16 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0008_alter_lettercomment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='slug',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
